spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/GitUser?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: tester
    password: test

  config:
    import: application-API-Key.yml
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.clientId}
            client-secret: ${google.clientSecret}