spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:mysql://${server.endpoint}:3306/GitUser?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${server.rdsID}
    password: ${server.rdsPW}

  config:
    import: application-API-Key.yml , server-URL.yml
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          naver:
            client-id: ${naver.clientId}
            client-secret: ${naver.clientSecret}
            redirect-uri: ${server.url}/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope:
              - name
              - email
              - profile_image
          google:
            client-id: ${google.clientId}
            client-secret: ${google.clientSecret}
            scope:
              - profile
              - email
            redirect-uri: ${server.url}/login/oauth2/code/google
          github:
            client-id: ${github.clientId}
            client-secret: ${github.clientSecret}
            redirect-uri: ${server.url}/login/oauth2/code/github